[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_usd_oracle = "GSwL85d5Pvvh8HreS3D7d6X3NmCZySbKmZBebF3oqCk3"
token_minter = "3eyjeU9ZaU2aVySwSNBQWPtkZnN2NtUNWDmpBfsMj4kn"

[programs.localnet]
sol_usd_oracle = "GSwL85d5Pvvh8HreS3D7d6X3NmCZySbKmZBebF3oqCk3"
token_minter = "3eyjeU9ZaU2aVySwSNBQWPtkZnN2NtUNWDmpBfsMj4kn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
litesvm = "node --import tsx/esm node_modules/.bin/mocha -t 1000000 \"tests/**/*.ts\""
test = "node --import tsx/esm node_modules/.bin/mocha -t 1000000 \"tests/**/*.ts\""
